#fix item.equip
ALTER TABLE `inventory` CHANGE `equip` `equip` MEDIUMINT UNSIGNED DEFAULT '0' NOT NULL;
ALTER TABLE `cart_inventory` CHANGE `equip` `equip` MEDIUMINT UNSIGNED DEFAULT '0' NOT NULL;
ALTER TABLE `storage` CHANGE `equip` `equip` MEDIUMINT UNSIGNED DEFAULT '0' NOT NULL;
ALTER TABLE `pet` CHANGE `equip` `equip` MEDIUMINT UNSIGNED DEFAULT '0' NOT NULL;